export const anomalies = [
    {
        id: 1,
        category: "API Response",
        question: "Which response contains the anomaly?",
        options: [
            { id: "A", label: "Response A", content: `{\n  "crew_id": 104,\n  "status": "active",\n  "fuel": 88\n}` },
            { id: "B", label: "Response B", content: `{\n  "crew_id": 105,\n  "status": "active",\n  "fuel": 65\n}` },
            { id: "C", label: "Response C", content: `{\n  "crew_id": 106,\n  "status": "active",\n  "fuel": -12\n}` },
        ],
        correct: "C",
        reason: "Fuel cannot be negative — sensor or input is corrupted by the impostor.",
    },
    {
        id: 2,
        category: "AI Output",
        question: "Which AI classification looks tampered with?",
        options: [
            { id: "A", label: "Classifier A", content: `label: "crewmate"\nconfidence: 0.92` },
            { id: "B", label: "Classifier B", content: `label: "impostor"\nconfidence: 1.87` },
            { id: "C", label: "Classifier C", content: `label: "crewmate"\nconfidence: 0.74` },
        ],
        correct: "B",
        reason: "Confidence scores must be between 0 and 1. A value of 1.87 is impossible.",
    },
    {
        id: 3,
        category: "System Log",
        question: "Which log entry indicates an anomaly?",
        options: [
            { id: "A", label: "Log A", content: `[12:01:04] O2 stable at 21%` },
            { id: "B", label: "Log B", content: `[12:01:07] Reactor temperature: 412°C` },
            { id: "C", label: "Log C", content: `[12:01:09] Crewmate login from sector 7 at 03:42 (future timestamp)` },
        ],
        correct: "C",
        reason: "A login timestamped in the future indicates clock tampering by the impostor.",
    },
    {
        id: 4,
        category: "Security Alert",
        question: "Which alert is the real intrusion?",
        options: [
            { id: "A", label: "Alert A", content: `Failed login: user=red, attempts=2` },
            { id: "B", label: "Alert B", content: `Privilege escalation: user=guest → root, source=internal_vent` },
            { id: "C", label: "Alert C", content: `Routine scan: 0 threats found` },
        ],
        correct: "B",
        reason: "Guest accounts must never escalate to root, especially from the vent system.",
    },
    {
        id: 5,
        category: "System Config",
        question: "Which configuration is unsafe?",
        options: [
            { id: "A", label: "Config A", content: `airlock.timeout = 30s\nairlock.auth = required` },
            { id: "B", label: "Config B", content: `reactor.coolant = enabled\nreactor.shutdown = manual` },
            { id: "C", label: "Config C", content: `cameras.enabled = false\nadmin.audit_log = disabled` },
        ],
        correct: "C",
        reason: "Disabling cameras AND audit logs removes all oversight — classic impostor cover-up.",
    },
];

export const debugs = [
    {
        id: 1,
        topic: "Array Index Error",
        language: "JavaScript",
        code: [
            "function lastCrewmate(crew) {",
            "  if (crew.length === 0) return null;",
            "  return crew[crew.length];",
            "}",
            "console.log(lastCrewmate(['red','blue']));",
        ],
        buggyLine: 3,
        explanation: "Arrays are zero-indexed. Should be crew[crew.length - 1].",
    },
    {
        id: 2,
        topic: "Infinite Loop",
        language: "JavaScript",
        code: [
            "let tasks = 5;",
            "while (tasks > 0) {",
            "  console.log('completing task', tasks);",
            "  tasks = tasks + 1;",
            "}",
            "console.log('done');",
        ],
        buggyLine: 4,
        explanation: "Counter increases instead of decreasing — the loop never terminates.",
    },
    {
        id: 3,
        topic: "Null Pointer Issue",
        language: "JavaScript",
        code: [
            "function getRole(crew) {",
            "  const profile = crew.profile;",
            "  const role = profile.role.toUpperCase();",
            "  return role;",
            "}",
            "getRole({});",
        ],
        buggyLine: 3,
        explanation: "profile is undefined — accessing .role throws. Needs a null check.",
    },
    {
        id: 4,
        topic: "API Validation Bug",
        language: "JavaScript",
        code: [
            "function createTask(req) {",
            "  const { title, points } = req.body;",
            "  if (!title) return { error: 'title required' };",
            "  return db.tasks.insert({ title, points });",
            "}",
        ],
        buggyLine: 4,
        explanation: "Missing validation on points — negative or huge values reach the DB.",
    },
    {
        id: 5,
        topic: "Security Vulnerability",
        language: "JavaScript",
        code: [
            "app.get('/crew/:id', (req, res) => {",
            "  const id = req.params.id;",
            "  const query = `SELECT * FROM crew WHERE id = ${id}`;",
            "  db.query(query).then(r => res.json(r));",
            "});",
        ],
        buggyLine: 3,
        explanation: "SQL injection — user input concatenated into the query. Use parameterized queries.",
    },
];